# Generated by Django 5.0.4 on 2024-05-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cliente_pais_origen_id_alter_pais_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.IntegerField(null=True),
        ),
    ]
