# Generated by Django 5.0.4 on 2024-05-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cliente_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='nombre',
        ),
    ]
