# Generated by Django 5.0.4 on 2024-05-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_pais_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='pais'),
        ),
    ]
