# Generated by Django 5.0.4 on 2024-05-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pais_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pais_origen_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais de origen'),
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
