# Generated by Django 5.0.4 on 2024-05-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cliente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='consulta',
            field=models.CharField(choices=[('consulta general', 'Consulta general'), ('Revision examenes', 'Revision examenes'), ('Psicologia', 'Psicologia')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais_origen',
            field=models.CharField(max_length=50, null=True, verbose_name='Pais de origen'),
        ),
    ]
