# Generated by Django 5.0.4 on 2024-05-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cliente_consulta_cliente_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.CharField(choices=[('consulta general', 'Consulta general'), ('Revision examenes', 'Revision examenes'), ('Psicologia', 'Psicologia')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='consulta',
        ),
        migrations.AddField(
            model_name='cliente',
            name='consulta_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.consulta', verbose_name='país de origen'),
        ),
    ]
