# Generated by Django 5.0.4 on 2024-05-01 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_consulta_remove_cliente_consulta_cliente_consulta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='consulta_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.consulta', verbose_name='tipo de consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='consulta',
            field=models.CharField(choices=[('consulta general', 'Consulta general'), ('Revision examenes', 'Revision examenes'), ('Psicologia', 'Psicologia')], max_length=200, null=True),
        ),
    ]
