# Generated by Django 5.0.4 on 2024-05-01 14:31

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cliente_consulta_id_alter_consulta_consulta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name_plural': 'países'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='consulta_id',
            field=models.ForeignKey(default=app.models.Pacientes, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.consulta', verbose_name='tipo de consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='consulta',
            field=models.CharField(choices=[('Consulta general', 'Consulta general'), ('Revision examenes', 'Revision examenes'), ('Psicologia', 'Psicologia')], max_length=200, null=True),
        ),
    ]
