# Generated by Django 5.0.4 on 2024-05-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_consulta_options_alter_cliente_consulta_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.IntegerField(null=True)),
                ('nacimiento', models.DateField(null=True)),
                ('pais_origen', models.CharField(max_length=50, null=True, verbose_name='Pais de origen')),
                ('profesion', models.CharField(choices=[('Medicina', 'Medicina'), ('', '')], max_length=50, null=True)),
                ('especialidad', models.CharField(max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.IntegerField(null=True)),
                ('nacimiento', models.DateField(null=True)),
                ('pais_origen', models.CharField(max_length=50, null=True, verbose_name='Pais de origen')),
                ('profesion', models.CharField(max_length=100, null=True)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50, null=True)),
                ('descripcion_puesto', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={},
        ),
        migrations.AddField(
            model_name='consulta',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='cedula',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='pais_origen',
            field=models.CharField(max_length=50, null=True, verbose_name='Pais de origen'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
