# Generated by Django 5.0.4 on 2024-05-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_medicos_personaladm_alter_consulta_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulta',
            new_name='Pacientes',
        ),
    ]
