# Generated by Django 5.0.4 on 2024-05-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_consulta_pacientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicos',
        ),
        migrations.DeleteModel(
            name='PersonalAdm',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
