# Generated by Django 5.0.4 on 2024-05-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_medicos_delete_personaladm_pacientes_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
